export const QUESTION_POOL: string[] = [
  "What's your hottest take on movies?",
  "If your job were a dish, what would it be and why?",
  "What's a famous dish from your culture?",
  "What's a lesser-known fact about your country?",
  "What's a stereotype about your culture?",
  "What's a stereotype about your job?",
  "Which popular movie do you think is mid, and why?",
  "What's a tradition you wish more people knew about?",
  "What holiday dish feels like home to you?",
  "What's a stereotype about your culture that's actually false?",
  "What word or phrase in your language do you say a lot, and what does it mean?",
  "What local superstition do you kind of believe?",
  "What law or custom where you live would outsiders find weird?",
  "What local scam should visitors watch for?",
  "What's your favorite rainy-day thing to do in your city?",
  "What's a slang term only locals use, and what does it mean?",
  "If your city were a smell, what would it be?",
  "What's your favorite book (right now)?",
  "Which movie do you wish you could see again for the first time, and why?",
  "Which city surprised you, and how?",
  "What souvenir do you actually use?",
  "What's one rule you live by?",
  "How would you define \"success\" in one sentence?",
  "What's a red flag you ignore every time?",
  "If your life were a genre, which would it be and why?",
  "What's a smell that instantly teleports you somewhere?",
  "What's the most \"you\" object on your desk, and why?",
  "If you could be born into a different religion than your current one, which would it be and why?",
  "Do you believe in a higher power? Why or why not (in one line)?",
  "Fate, free will, or a messy mix—what do you lean toward, and why?",
  "Do you think life has a purpose? Why or why not?",
  "What's a small ritual that centers you?",
  "What verse or quote stays with you?",
  "What's a belief you've outgrown, and what replaced it?",
  "What festival or holiday from your tradition would you share with everyone, and why?",
  "What one-sentence blessing would you give a friend?"
];
